### ISSUE TITLE
Large Vehicles cannot move through garage doors.

### ISSUE THREAD

**Issue by CodyProductions1234** [SmashPhil/Vehicle-Framework#110]
**Describe the bug**
As the title states, large vehicles (like the big rig from the Tier 3 mod, all of the vehicles from the Synthetic vehicle mod, I will add a list of vehicles affected when I test this further.) cannot go through the garage doors. Auto or Otherwise.

**To Reproduce**
1. Construct one of the affected vehicles. (In this case the big rig from Tier 3.) And a smaller vehicle such as the Traveler.
2. Construct a small room with a 1 x 5 garage door to fit both vehicles.
3. Open the garage door.
4. Have a pawn attempt to drive out the big rig. Then do the same with the smaller vehicle.

**Screenshots**
TBA

**Additional context**
TBA

**Comment by CodyProductions1234** [comment]
EDIT, it appears to be fixed, but as to how or why I do not know.

**Comment by SmashPhil** [comment]
It's a region dirtying issue, which has had many causes in the past.  I have a fix out for it on unstable-branch, which _should_ be the last one.  As for it suddenly going away, that generally happens when you do a force reload on the entire region grid such as from the DevMode tab in the VF mod settings, or by reloading the save.
