### ISSUE TITLE
Drivers and pathfinding

### ISSUE THREAD

**Issue by Roshag** [SmashPhil/Vehicle-Framework#113]
I think there should be some soft requirements for a pawn to drive a car except for being able to walk. I haven't checked if pawn without arms can drive, but children can as soon as they can walk.
And caravan vehicles drive over every pawn on their way when leaving the map. What about some optional setting to avoid hitting colonists, colony animals and allies? Or being able to create preferable paths so vehicles use player-built roads instead of driving straight to exit?

**Comment by Roshag** [comment]
Okay, armless pawn can enter vehicle as a driver, but cannot drive

**Comment by SmashPhil** [comment]
> I think there should be some soft requirements for a pawn to drive a car except for being able to walk.
There is, it's manipulation.  This is the same way vanilla handles most tasks.  I may or may not add requirements down the road for children however I haven't touched the DLC content yet so it's not something that I've intentionally done either.

> And caravan vehicles drive over every pawn on their way when leaving the map. What about some optional setting to avoid hitting colonists, colony animals and allies?
There already is one, it's the same behavior that causes pawns to flee out of the way.  Increasing that distance won't fix it, what if a vehicle turns suddenly? What if a vehicle is too fast? This is also applicable to raiders since if pawns can never be hit then there's no point in having the mechanic whatsoever.  This was a heavily requested feature which is why it was added.  You can disable it in the mod settings.

> Or being able to create preferable paths so vehicles use player-built roads instead of driving straight to exit?
Vehicles check the avoidal grid, so a mod like Path Avoid would do exactly this.

**Comment by Roshag** [comment]
Thanks, I'll try Path Avoid. But I encountered another issue with caravan that probably can also be fixed with Path Avoid or just building walls around road. While caravan was leaving the map, driver hit an animal and died. But this could be an issue with vehicle itselves.
