### ISSUE TITLE
Caravan cant form due to "No Path"

### ISSUE THREAD

**Issue by GodM0d3** [SmashPhil/Vehicle-Framework#118]
**Describe the bug**
Hello, im not sure if this bug is caused by vanilla vehicles expanded or the framework itself.
When I launch a caravan with multiple vehicles (4) they apparently all want to go to one spot, which is blocked by the vehicles arriving first, so it just starts to spam no path (and kills the wheels at it constantly accelerates and breaks as it is blocked)
Bug doesnt occur always. Sometimes the vehicles just "teleport" out of the map even if they are still a bit away. And its possible to work around it by launching the caravans split in half. But as this still seems in development i guess that could be added to the bug tracker

**To Reproduce**
1. Create a caravan with multiple vehicles.
2. Wait for caravan to arrive at map edge
3. Message spams "No Path"
4. Manually moving vehicles doesnt help either
5. There were trees near the point the caravan choose to form, unclear whether that contributes

**Additional context**
I am using Vanilla Vehicles expanded. 
Propably irrelevant: The cars are: Bunsen, Highwayman, Mule, Roadkill.

**Comment by SmashPhil** [comment]
many vehicles in a caravan can sometimes be a bit cumbersome on the pathfinding since they get in the way of each other when pathfinding to the exit point.  Like you said, it's still WIP.  I'll look into this a bit later, temporary workaround is to send the caravans instantly or in smaller groups and merge on the world map.
