### ISSUE TITLE
Wisent From Vanilla Vehicles Expanded Unable To Correctly Pathfind

### ISSUE THREAD

**Issue by Oclas** [SmashPhil/Vehicle-Framework#123]
I'll keep this relatively short and attach some screenshots to prove the issue. I recently downloaded the Vehicle Framework mod and Vanilla Vehicles Expanded mods over on the Steam Workshop and the first vehicle that I went to go build and use from there was the Wisent. It is not currently capable of pathfinding to separate areas it seems. Even removing walls/doors didn't fix the pathfinding issue. Normally I would assume to leave a bug report on that mod but the mod author directed the complaint to the Vehicle Framework mod so here I am. I am not the only one who has run into this issue; on the Vanilla Vehicles expanded mod page there is at least one other poster who has run into this issue.
Screenshot descriptions are as follows,
1. 
![bugreport1](https://github.com/SmashPhil/Vehicle-Framework/assets/113310196/cc918b42-c851-49fa-9dd6-0172083b23db)
Screenshot simply shows vehicle is on and has fuel.
2. 
![bugreport2](https://github.com/SmashPhil/Vehicle-Framework/assets/113310196/33b6e7e4-c08b-4b62-9daa-32e3c21e7c98)
Screenshot shows that the garage door is open and should not be obstructing any pathfinding.
3. 
![bugreport3](https://github.com/SmashPhil/Vehicle-Framework/assets/113310196/d412508b-2bad-4177-8abc-cc0d5d96bcff)
Screenshot shows that vehicle is not capable of pathfinding through the garage door to the exterior of the base.
4. 
![bugreport4](https://github.com/SmashPhil/Vehicle-Framework/assets/113310196/b721bbf1-c884-4c77-a561-742228a85c41)
Screenshot shows that vehicle is capable of pathfinding on interior of base via a short distance route.
5. 
![bugreport5](https://github.com/SmashPhil/Vehicle-Framework/assets/113310196/efc865e5-d229-4a97-b4f5-8789d5b584e8)
Screenshot shows that vehicle is capable of long distance pathing on interior of base.
6. 
![bugreport6](https://github.com/SmashPhil/Vehicle-Framework/assets/113310196/f9a8e335-4982-4947-8bc1-11838e7e8829)
Screenshot shows that removing garage door does not fix the issue.
Hopefully the formatting here is alright as I do not frequently use github. I'll try to remember to check back up on this later if further information is required.

**Comment by SmashPhil** [comment]
This is a known bug, and I have a potential fix up on the unstable build.  The issue is region dirtying, specifically in this case the Wisent and Smuggler are incorrectly sharing regions with the Frog and Toad, which don't update reachability since they can't move.

Next update _should_ fix it, but there may always be other issues since 'region dirtying' is a pretty over-arching mechanic so many different bugs can cause incorrect updating.  For now, reloading your game will force-generate the regions properly, though keep in mind that the moment you build new walls or open / close the garage you'll encounter the issue again.

Next update isn't too far off
