### ISSUE TITLE
cant select where i wanna land on a tile (edge or center)

### ISSUE THREAD

**Issue by StarlordKK** [SmashPhil/Vehicle-Framework#145]
**Describe the bug**
cant select where i wanna land on a tile (edge or center)
thie dialog doenst pop up

**To Reproduce**
1. Build Helicopter
2. Launch
3. Select tile on world map
4. context menu for selecting edge/center doesnt show

**Comment by SmashPhil** [comment]
I'd need logs and screenshots in order to look into it, I can't reproduce this on my side with any site.  It's possible this was fixed and I didn't check back on this bug report, or it's for a modded site that isn't accounted for by VF.  

Feel free to re-open it if you provide logs + screenshots and can still reproduce it.
